version: '2'

services:
   IMRUdb:
     image: mariadb:10.3.0
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somedbpass
       MYSQL_DATABASE: codeigniter
       MYSQL_USER: codeigniter
       MYSQL_PASSWORD: codeigniter
     mem_limit: 1024MB
   IMRUtomcat_alpine:
     depends_on:
       - IMRUdb
     image: benspelledabc/imru-tomcat-alpine
     ports:
       - "80:8080"
       - "443:443"
     restart: always
     mem_limit: 1024MB

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     environment:
       - MYSQL_ROOT_PASSWORD:"somedbpass"
       - PMA_HOST=IMRUdb
     restart: always
     ports:
       - "8080:80"

volumes:
    db_data:
