version: '3'

services:
   IMRUdb:
     image: mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somedbpass
       MYSQL_DATABASE: codeigniter
       MYSQL_USER: codeigniter
       MYSQL_PASSWORD: codeigniter

   IMRUtomcat:
     depends_on:
       - IMRUdb
     image: benspelledabc/imru-tomcat:latest
     ports:
       - "80:8080"
     restart: always
volumes:
    db_data:
